#!/bin/sh

# make sure we never run 2 rsync at the same time
lockfile="/tmp/apache-mirror.lock"
if [ -z "$flock" ] ; then
  exec env flock=1 flock -n $lockfile "$0" "$@"
fi

SOURCE=rsync://rsync.apache.org/apache-dist 
TARGET=/data/apache/

mkdir -p "$TARGET"
/usr/bin/rsync \
        --verbose \
        --progress \
        --exclude-from /etc/rsync/apache.exclude-list \
        --archive \
        --update \
        --hard-links \
        --delete \
        --delete-after \
        --delay-updates \
        --timeout=600 \
        "$SOURCE" "$TARGET"

#        --exclude-from /etc/rsync/apache.exclude-list \
