#!/bin/sh

# make sure we never run 2 rsync at the same time
lockfile="/tmp/alpine-mirror.lock"
if [ -z "$flock" ] ; then
  exec env flock=1 flock -n $lockfile "$0" "$@"
fi

SOURCE=rsync://rsync.alpinelinux.org/alpine/ 
TARGET=/var/www/alpine-repo/

mkdir -p "$TARGET"
/usr/bin/rsync \
        --recursive \
        --verbose \
        --progress \
        --include-from /data/mirrors/scripts/alpine/include-list \
        --archive \
        --update \
        --hard-links \
        --delete \
        --delete-after \
        --delay-updates \
        --timeout=600 \
        "$SOURCE" "$TARGET"
